service: basic-serverless-lambda

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-west-1

functions:
  hello:
    handler: src/handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 128 # mb